# Esta es una imagen base de Nginx
FROM nginx:alpine 
# copia el archivo index.html al directori de nginx
COPY index.html /usr/share/nginx/html/index.html
# Exponer el puerto 80 para acceder desde fuera
EXPOSE 80